# Generated by Django 3.1.7 on 2021-03-27 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=31)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True, verbose_name='user friendly url')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(help_text='Project website', max_length=255)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='quiz.Category')),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['title'],
                'get_latest_by': 'date_added',
            },
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=255)),
                ('summary', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=63, unique=True, verbose_name='user friendly url')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='projects.project')),
                ('quiz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
                'unique_together': {('slug', 'project')},
            },
        ),
    ]
