# Generated by Django 3.1.7 on 2021-03-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210314_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelink',
            name='project',
        ),
        migrations.AddField(
            model_name='articlelink',
            name='projects',
            field=models.ManyToManyField(related_name='articles', to='projects.Project'),
        ),
    ]
