# Generated by Django 3.1.7 on 2021-04-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project_default.jpg', upload_to='project_pic'),
        ),
    ]
