# Generated by Django 3.1.7 on 2021-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210409_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='telegram_id',
            field=models.CharField(blank=True, default='username', help_text="please input project's telegram id", max_length=100, null=True),
        ),
    ]
