# Generated by Django 3.1.7 on 2021-05-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='pub_date',
            field=models.DateField(help_text='DD/MM/YYYY', verbose_name='date published'),
        ),
    ]
