# Generated by Django 3.0.7 on 2021-07-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210610_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', max_length=9),
        ),
    ]
