# Generated by Django 3.1.7 on 2021-03-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210313_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.SlugField(default='default', help_text='a user friendly url', max_length=31, unique=True, verbose_name='user friendly url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(related_name='quizzes', to='quiz.Category'),
        ),
    ]
