# Generated by Django 3.1.7 on 2021-04-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210327_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='quiz_default.jpg', upload_to='quiz_pic'),
        ),
    ]
