# Generated by Django 3.1.7 on 2021-04-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210409_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_default.jpg', upload_to='category_pic'),
        ),
    ]
