# Generated by Django 3.0.7 on 2021-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='recipient',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
