# Generated by Django 3.1.7 on 2021-05-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Passed'),
        ),
    ]
