# Generated by Django 3.1.7 on 2021-05-02 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_sitting_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitting',
            name='passed',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Percentage required to pass exam.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Pass Mark'),
        ),
    ]
