# Generated by Django 3.1.7 on 2021-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, default='username', help_text='please input your correct telegram username', max_length=100, null=True),
        ),
    ]
