# Generated by Django 3.1.7 on 2021-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, default='username', help_text='please input your correct telegram username to connect with friends, fellow quiz takers, and quiz masters', max_length=100, null=True),
        ),
    ]
