# Generated by Django 3.1.7 on 2021-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210412_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(help_text='Please ensure you submit waves address generated using waves.exchange', max_length=35),
        ),
    ]
