# Generated by Django 3.0.7 on 2021-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(help_text='Please ensure you submit waves address generated using AMADI wallet', max_length=35),
        ),
    ]
