# Generated by Django 3.0.7 on 2021-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210930_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(help_text='Please ensure you submit waves address generated using AMADI wallet or waves.exchange', max_length=35),
        ),
    ]
